name: PHPUnit

on:
  push:
    branches:
      - develop
      - action-test3
  pull_request:
    branches:
      - develop
      - '4.*'

jobs:

  tests:
    runs-on: ubuntu-latest

    #if: ${{ contains(github.event.head_commit.message, '[skip ci]') == 'false' || (matrix.experimental == 'true' && startsWith(github.base_ref, '4.')) }}
    
    name: PHP ${{ matrix.php-versions }} - ${{ matrix.db-platforms }}

    if: ${{ matrix.experimental == 'true' && startsWith(github.base_ref, '4.') }}

    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
        db-platforms: ['MySQLi', 'Postgre', 'SQLite3']
        experimental: [false]
        include:
          - php-versions: '8.0'
            db-platforms: 'MySQLi'
            composer-options: '--ignore-platform-reqs'
            experimental: true
          - php-versions: '8.0'
            db-platforms: 'Postgre'
            composer-options: '--ignore-platform-reqs'
            experimental: true
          - php-versions: '8.0'
            db-platforms: 'SQLite3'
            composer-options: '--ignore-platform-reqs'
            experimental: true

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          extensions: imagick
          coverage: none
        env:
          update: true

      - name: Install Memcached
        uses: niden/actions-memcached@v7

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader ${{ matrix.composer-options }}
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}     

      - name: Test with PHPUnit
        run: script -e -c "vendor/bin/phpunit -v"
        env:
          DB: ${{ matrix.db-platforms }}
          TERM: xterm-256color

      - name: Run Coveralls
        run: |
          composer global require twinh/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: PHP ${{ matrix.php-versions }}

  coveralls-finish:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
